[package]
name = "coblox-ffi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
build = "build.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
coblox-core = { path = "../coblox-core" }
uniffi = { version = "0.32.0", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.32.0", features = ["build"] }

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"

[lints]
workspace = true
