"""Recompute published Coblox hashes from the bytes the documents actually carry.

Versioned because [REVIEW-014] RF-007 found the transcript of [SPEC-009] citing
`scratch/*.py` scripts that were never in the tree: evidence nobody else can
re-run is not evidence.

Method, from `docs/protocol/README.md` §"Hash preimage registry":

    <kind>_hash = H(domain || chain_id_32 || JCS(UnsignedProtocolDocument))
    app_leaf    = H(0x13 || account_key || u64be(balance) || u64be(nonce)
                         || lifecycle_u8 || u64be(suspension_effective_epoch))

`H` is SHA-256 and `JCS` is RFC 8785 canonical JSON. Every `PD-0` body is a flat
object of ASCII keys and string values, for which JCS reduces to sorted keys,
no whitespace, and minimal escaping — which is what `json.dumps` produces with
`sort_keys=True` and compact separators.

    python sim/tools/protocol_hashes.py

**The expected values are read from `docs/protocol/README.md`, not copied into
this file.** They used to be copied, and that is how [SPEC-009] shipped a stale
constant that made this tool report a mismatch which did not exist — the false
positive [ADR-012] cites when it requires a guard to be proved in the negative.
A tool that carries its own copy of the oracle can disagree with the oracle
while looking authoritative. The `coblox-core` conformance suite still keeps a
hand transcription, and that one is deliberate for the opposite reason: a suite
whose expectation is generated by the implementation under test asserts nothing.
`sim/tools/published_artifacts.py` check C5 is what keeps the transcription and
the document from drifting apart.

Each section validates the method on values this pass did **not** change before
reporting the ones it did, which is the discipline `GATE-FIXTURES-RECOMPUTED`
exists to enforce: a procedure that cannot reproduce an untouched value is not
evidence for a touched one.
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import re
import sys

CHAIN_ID = bytes(32)

DOMAINS = {
    "enrollment_parameters": b"coblox-enrollment-parameter-set-v0\x00",
    "reward_policy": b"coblox-reward-policy-v0\x00",
    "hosting_rate_card": b"coblox-hosting-rate-card-v0\x00",
    "consensus_parameters": b"coblox-consensus-parameters-v0\x00",
}

README = (
    pathlib.Path(__file__).resolve().parents[2] / "docs" / "protocol" / "README.md"
)

# The row of the registry table that publishes each value, by its `Hash` cell.
REGISTRY_ROWS = {
    "enrollment_parameters": "`parameter_set_hash`",
    "reward_policy": "`policy_hash`",
    "hosting_rate_card": "`hosting_rate_card_hash`",
    "consensus_parameters": "`consensus_parameters_hash`",
    "app_leaf": "`app_leaf`",
    "account_key_app": "`account_key` (app)",
}


def read_registry() -> dict[str, str]:
    """Read the expected values out of the published table.

    A missing row is a hard error rather than a skipped check: the whole point
    of reading the document is that this tool cannot silently keep asserting a
    value the document no longer publishes.
    """
    text = README.read_text(encoding="utf-8")
    published: dict[str, str] = {}
    for key, cell in REGISTRY_ROWS.items():
        pattern = re.compile(
            r"^\| " + re.escape(cell) + r" \| [^|]+ \| `(sha256:[0-9a-f]{64})` \|$",
            re.MULTILINE,
        )
        match = pattern.search(text)
        if match is None:
            raise SystemExit(
                f"docs/protocol/README.md publishes no registry row for {cell!r}; "
                f"this tool refuses to assert a value the document does not carry"
            )
        published[key] = match.group(1)
    return published


PUBLISHED = read_registry()

ENROLLMENT_BODY = {
    "pow_algorithm": "argon2id-leading-zero-bits-v0",
    "difficulty_bits": "4",
    "memory_kib": "65536",
    "iterations": "3",
    "lanes": "4",
    "tag_length_bytes": "32",
    "max_request_age_ms": "1",
    "max_future_skew_ms": "1",
    "recent_block_window": "1",
}

REWARD_BODY_KEYS = (
    "reward_epoch_ms",
    "existence_fund_microtokens_per_epoch",
    "availability_microtokens_per_unit",
    "storage_microtokens_per_byte_epoch",
    "compute_microtokens_per_million_fuel",
    "publisher_microtokens_per_active_subscriber",
    "publisher_reward_cap_numerator",
    "publisher_reward_cap_denominator",
    "storage_units_per_contribution_unit",
    "compute_units_per_contribution_unit",
    "validator_eligibility_threshold_units",
    "validator_eligibility_window_epochs",
    "validator_eligibility_min_issuers",
)

HOSTING_BODY = {
    "billing_epoch_ms": "1",
    "minimum_billable_epochs": "1",
    "microtokens_per_replica_epoch": "1",
    "microtokens_per_gib_epoch": "1",
    "microtokens_per_million_fuel": "1",
}

CONSENSUS_BODY = {
    "max_clock_drift_ms": "1",
    "max_envelope_validity_ms": "1",
    "replay_cache_entries_per_peer": "1",
    "replay_cache_entries_global": "1",
    "max_weak_subjectivity_age_ms": "1",
    "max_current_balance_age_ms": "1",
    "app_suspension_notice_epochs": "1",
    "min_revocation_effective_delay_blocks": "1",
    "election_epoch_blocks": "4",
    "candidacy_close_blocks": "3",
    "election_entropy_blocks": "2",
    "validator_min_set_size": "8",
    "validator_target_set_size": "12",
    "validator_max_set_size": "12",
    "validator_churn_cap_seats": "3",
    "validator_max_consecutive_terms": "4",
    "validator_cooldown_epochs": "1",
    "validator_min_capture_epochs": "1",
}


def reward_body(availability: str) -> dict[str, str]:
    body = {k: "1" for k in REWARD_BODY_KEYS}
    body["availability_microtokens_per_unit"] = availability
    body["publisher_reward_cap_denominator"] = "2"
    body["validator_eligibility_min_issuers"] = "2"
    return body


def jcs(obj) -> bytes:
    return json.dumps(obj, sort_keys=True, separators=(",", ":"),
                      ensure_ascii=False).encode("utf-8")


def document_hash(kind: str, body: dict) -> str:
    unsigned = {
        "schema_version": "0.1",
        "document_kind": kind,
        "network_id": "fixture",
        "chain_id": "sha256:" + CHAIN_ID.hex(),
        "sequence": "1",
        "activation_height": "1",
        "body": body,
    }
    digest = hashlib.sha256(DOMAINS[kind] + CHAIN_ID + jcs(unsigned)).hexdigest()
    return "sha256:" + digest


def sha(*parts: bytes) -> str:
    digest = hashlib.sha256()
    for part in parts:
        digest.update(part)
    return "sha256:" + digest.hexdigest()


def u64be(value: int) -> bytes:
    return value.to_bytes(8, "big")


# --- APP-0, the fixture added for [DEBT-012] --------------------------------
#
# "`APP-0` is an **app** account in state `suspended`, for `app_id` `99`
# repeated 32 bytes, with `balance_microtokens` 1, `account_nonce` 1 and
# `suspension_effective_epoch` 1; its `lifecycle_u8` is therefore `0x03`".
APP0_APP_ID = bytes([0x99]) * 32
APP0_BALANCE = 1
APP0_NONCE = 1
APP0_SUSPENSION_EPOCH = 1
LIFECYCLE_SUSPENDED = 0x03

# Published before this pass and untouched by it, so they are what validates
# the tagged-tree method before it is used on a new value.
REVOCATION_NODE_ID = b"cblx1revokedfixture"
REVOCATION_EFFECTIVE_HEIGHT = 50


def app0_account_key() -> bytes:
    return hashlib.sha256(
        b"coblox-account-key-v0\x00" + b"\x01" + APP0_APP_ID
    ).digest()


def report(label: str, computed: str, published: str) -> bool:
    ok = computed == published
    print(f"  {label:<28} {'MATCH' if ok else 'MISMATCH'}")
    print(f"    published {published}")
    print(f"    computed  {computed}")
    return ok


def main() -> int:
    ok = True

    print("Governed protocol documents. None of the four changed in this pass,")
    print("so all four are method validation:")
    for kind, body in (
        ("enrollment_parameters", ENROLLMENT_BODY),
        ("hosting_rate_card", HOSTING_BODY),
        ("consensus_parameters", CONSENSUS_BODY),
        ("reward_policy", reward_body("0")),
    ):
        ok &= report(kind, document_hash(kind, body), PUBLISHED[kind])

    print()
    print("The reward fixture with the pre-[ADR-010] availability tariff, for")
    print("comparison - this is the shape the validity rule of [ADR-010] forbids:")
    print(f"    availability=1 -> {document_hash('reward_policy', reward_body('1'))}")

    print()
    print("Tagged trees. Method validation on the two values published before")
    print("this pass and untouched by it:")
    ok &= report(
        "empty revocation_root H(0x33)",
        sha(b"\x33"),
        "sha256:4e07408562bedb8b60ce05c1decfe3ad16b72230967de01f640b7e4729b49fce",
    )
    ok &= report(
        "revocation_leaf REVL-0",
        sha(
            b"\x30",
            len(REVOCATION_NODE_ID).to_bytes(4, "big"),
            REVOCATION_NODE_ID,
            u64be(REVOCATION_EFFECTIVE_HEIGHT),
        ),
        "sha256:7fb1f4024627c413cbf70b49a390b6d31778e667e86042864c4bed107cd52497",
    )

    print()
    print("The fixture this pass added, computed with that validated method")
    print("from the bytes the document now carries:")
    account_key = app0_account_key()
    ok &= report(
        "account_key (app) APP-0",
        "sha256:" + account_key.hex(),
        PUBLISHED["account_key_app"],
    )
    ok &= report(
        "app_leaf APP-0",
        sha(
            b"\x13",
            account_key,
            u64be(APP0_BALANCE),
            u64be(APP0_NONCE),
            bytes([LIFECYCLE_SUSPENDED]),
            u64be(APP0_SUSPENSION_EPOCH),
        ),
        PUBLISHED["app_leaf"],
    )

    print()
    print("The same leaf under the encodings the document does NOT use, so the")
    print("choice is visible as a choice and not as an accident:")
    for name, byte in (
        ("reserved 0x00 (invalid)", 0x00),
        ("provisional pre-[DEBT-012] suspended = 2", 0x02),
    ):
        print(
            f"    {name:<42} "
            + sha(
                b"\x13",
                account_key,
                u64be(APP0_BALANCE),
                u64be(APP0_NONCE),
                bytes([byte]),
                u64be(APP0_SUSPENSION_EPOCH),
            )
        )

    print()
    print(f"every published value reproduced: {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
